import Head from 'next/head'
import Image from 'next/image'
import AppBulletList from '../bullet_components/AppBulletList.js'
import AppNavBar from '../bullet_components/AppNavBar.js'

export default function Home() {
  let title = "My Bullet Journal"
  let firstbulletlist = {
    title : "Backlog",
    bullet_list : [
      {key : "1", type : "event", content : "latest pnpm version realease"},
      {key : "2", type : "event", content : "oriented programming class"},
      {key : "3", type : "task", content : "clean my room"},
      {key : "4", type : "task", content : "join scrum meeting"}
    ]
  }
  let secondbulletlist = {
    title : "Doing",
    bullet_list : [
      {key : "1", type : "event", content : "olympiads awards cerimony"},
      {key : "2", type : "event", content : "newest music album release date"},
      {key : "3", type : "task", content : "help my little brother's homework"},
      {key : "4", type : "task", content : "take the garbage out"}
    ]
  }
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppNavBar title={title}/>
        <AppBulletList title={firstbulletlist.title} bullet_list={firstbulletlist.bullet_list}/>
        <AppBulletList title={secondbulletlist.title} bullet_list={secondbulletlist.bullet_list}/>
      </main>
    </div>
  )
}
